In [58]:
import tensorflow as tf
import numpy as np
import os
from sklearn.metrics import classification_report, confusion_matrix

In [59]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [60]:
from tensorflow.keras.models import load_model

CROP_NAME = "Brinjal"

model_path = f"/content/drive/MyDrive/Ganpat_hackathon_2026/ML1/Train_model/{CROP_NAME}_model.keras"
model = load_model(model_path)

In [61]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

test_dir = f"/content/drive/MyDrive/Ganpat_hackathon_2026/ML1/split_dataset/test/{CROP_NAME}"

test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=16,
    class_mode='categorical',
    shuffle=False
)

Found 52 images belonging to 5 classes.


In [62]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

test_dir = f"/content/drive/MyDrive/Ganpat_hackathon_2026/ML1/split_dataset/test/{CROP_NAME}"

test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=16,
    class_mode='categorical',
    shuffle=False
)

Found 52 images belonging to 5 classes.


In [63]:
import numpy as np

predictions = model.predict(test_data)
y_pred = np.argmax(predictions, axis=1)
y_true = test_data.classes

4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 527ms/step


In [64]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# Get class labels in order of their numerical index
class_labels = [None] * len(test_data.class_indices)
for name, idx in test_data.class_indices.items():
    class_labels[idx] = name

unique_labels = np.unique(y_true)
filtered_class_labels = [class_labels[i] for i in unique_labels]

print(classification_report(y_true, y_pred, labels=unique_labels, target_names=filtered_class_labels))

                       precision    recall  f1-score   support

       Bacrerial_Wilt       1.00      1.00      1.00         5
 Cercospora_Leaf_spot       1.00      1.00      1.00        10
              Healthy       0.88      1.00      0.94        22
               Mosaic       1.00      0.75      0.86         8
Phomopsis_Leaf_Blight       1.00      0.86      0.92         7

             accuracy                           0.94        52
            macro avg       0.98      0.92      0.94        52
         weighted avg       0.95      0.94      0.94        52



In [65]:
cm = confusion_matrix(y_true, y_pred)
print(cm)

[[ 5  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 22  0  0]
 [ 0  0  2  6  0]
 [ 0  0  1  0  6]]


In [66]:
loss, acc = model.evaluate(test_data)
print("Test Accuracy:", acc)

4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 722ms/step - accuracy: 0.9423 - loss: 0.2259
Test Accuracy: 0.942307710647583


In [68]:
import pandas as pd

data = {
    'Crop': ['Brinjal', 'Castor', 'Cumin', 'Guava', 'Papaya'],
    'Accuracy': [0.94, 0.80, 0.99, 0.88, 0.72]
}

accuracy_df = pd.DataFrame(data)
display(accuracy_df)

,Crop,Accuracy
0,Brinjal,0.94
1,Castor,0.80
2,Cumin,0.99
3,Guava,0.88
4,Papaya,0.72
